server:
   port: 2076

spring:
  rsocket:
    server:
     transport: TCP
     mapping-path: /rsocket

db:
  url: influxdb
  name: iotdb
  port: 8086
  username: root
  password: root
  store_metrics: 3d
  metricsEnabled: true
